"""add saved_tracks to user_top_content

Revision ID: aab5a5380595
Revises: ec79c85c16aa
Create Date: 2026-06-28 10:45:58.289355

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'aab5a5380595'
down_revision = 'ec79c85c16aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_top_content', sa.Column('saved_tracks', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_top_content', 'saved_tracks')
    # ### end Alembic commands ###
